apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: containerpoc
    name: containerpoc
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: containerpoc
    name: containerpoc
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: containerpoc:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/wael2000/containerpoc.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:4
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: zwY1MV2BlhjqGlJpulrF
      type: GitHub
    - generic:
        secret: 7OggXSoJNtMoztXsT3dL
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: containerpoc
    name: containerpoc
  spec:
    replicas: 1
    selector:
      app: containerpoc
      deploymentconfig: containerpoc
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.containerpoc.image.entrypoint: '["container-entrypoint","/bin/sh","-c","$STI_SCRIPTS_PATH/usage"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: containerpoc
          deploymentconfig: containerpoc
      spec:
        containers:
        - image: containerpoc:latest
          name: containerpoc
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: COUCHBASE
            value: ${COUCHBASE}
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - containerpoc
        from:
          kind: ImageStreamTag
          name: containerpoc:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: containerpoc
    name: containerpoc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: containerpoc
      deploymentconfig: containerpoc
  status:
    loadBalancer: {}
kind: List
metadata: {}
